language: node_js
node_js:
- '10'
- '9'
cache:
  directories:
  - node_modules
script:
  - yarn lint
  - yarn test
  - yarn compile
after_success:
  - yarn coverage
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    repo: guthega/log_receiver
    node: '10'
